-- =============================================================================
-- SISTEMA DE PROCESSOS ADMINISTRATIVOS
-- Estrutura do banco de dados
-- PostgreSQL 18 | Nomenclatura: DAAED_MAD_Guia_Modelagem_Dados
-- =============================================================================
-- Execução: psql -U postgres -h localhost -p 5434 -f 01_estrutura.sql

\c processos

-- =============================================================================
-- SEQUENCES
-- =============================================================================

CREATE SEQUENCE SQ_TB_PESSOA_FISICA_CO_SEQ
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE SQ_TB_PESSOA_JURIDICA_CO_SEQ
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE SQ_TB_USUARIO_CO_SEQ
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE SQ_TB_SETOR_CO_SEQ
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE SQ_TB_ANALISTA_CO_SEQ
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE SQ_TB_PROCESSO_CO_SEQ
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE SQ_RL_PROCESSO_PARTE_CO_SEQ
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE SQ_TB_REGISTRO_CO_SEQ
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE SQ_TH_TRAMITACAO_CO_SEQ
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- =============================================================================
-- TABELAS DE DOMÍNIO
-- (PK por código textual; sem sequence)
-- =============================================================================

CREATE TABLE TB_SITUACAO_PROCESSO (
    CO_SITUACAO_PROCESSO    VARCHAR(20)     NOT NULL,
    DS_SITUACAO             VARCHAR(100)    NOT NULL,
    ST_REGISTRO_ATIVO       VARCHAR(1)      NOT NULL DEFAULT 'S',
    CONSTRAINT PK_TB_SITUACAO_PROCESSO
        PRIMARY KEY (CO_SITUACAO_PROCESSO),
    CONSTRAINT CK_TB_SIT_PROC_ST_REG_ATIVO
        CHECK (ST_REGISTRO_ATIVO IN ('S', 'N'))
);

CREATE TABLE TB_TIPO_PARTE (
    CO_TIPO_PARTE           VARCHAR(30)     NOT NULL,
    DS_TIPO_PARTE           VARCHAR(100)    NOT NULL,
    ST_REGISTRO_ATIVO       VARCHAR(1)      NOT NULL DEFAULT 'S',
    CONSTRAINT PK_TB_TIPO_PARTE
        PRIMARY KEY (CO_TIPO_PARTE),
    CONSTRAINT CK_TB_TIPO_PARTE_ST_REG_ATIVO
        CHECK (ST_REGISTRO_ATIVO IN ('S', 'N'))
);

-- =============================================================================
-- TABELAS DE NEGÓCIO
-- =============================================================================

CREATE TABLE TB_PESSOA_FISICA (
    CO_SEQ_PESSOA_FISICA    BIGINT          NOT NULL DEFAULT NEXTVAL('SQ_TB_PESSOA_FISICA_CO_SEQ'),
    NO_PESSOA_FISICA        VARCHAR(200)    NOT NULL,
    NU_CPF                  VARCHAR(11)     NOT NULL,
    DT_NASCIMENTO           DATE,
    DS_EMAIL                VARCHAR(200),
    NU_TELEFONE             VARCHAR(20),
    DS_LOGRADOURO           VARCHAR(200),
    DS_COMPLEMENTO          VARCHAR(100),
    NO_BAIRRO               VARCHAR(100),
    NO_MUNICIPIO            VARCHAR(100),
    SG_UF                   VARCHAR(2),
    NU_CEP                  VARCHAR(8),
    ST_REGISTRO_ATIVO       VARCHAR(1)      NOT NULL DEFAULT 'S',
    CONSTRAINT PK_TB_PESSOA_FISICA
        PRIMARY KEY (CO_SEQ_PESSOA_FISICA),
    CONSTRAINT UK_TB_PESSOA_FISICA_NU_CPF
        UNIQUE (NU_CPF),
    CONSTRAINT CK_TB_PF_ST_REGISTRO_ATIVO
        CHECK (ST_REGISTRO_ATIVO IN ('S', 'N'))
);

CREATE TABLE TB_PESSOA_JURIDICA (
    CO_SEQ_PESSOA_JURIDICA  BIGINT          NOT NULL DEFAULT NEXTVAL('SQ_TB_PESSOA_JURIDICA_CO_SEQ'),
    NO_RAZAO_SOCIAL         VARCHAR(200)    NOT NULL,
    NO_NOME_FANTASIA        VARCHAR(200),
    NU_CNPJ                 VARCHAR(14)     NOT NULL,
    DS_EMAIL                VARCHAR(200),
    NU_TELEFONE             VARCHAR(20),
    DS_LOGRADOURO           VARCHAR(200),
    DS_COMPLEMENTO          VARCHAR(100),
    NO_BAIRRO               VARCHAR(100),
    NO_MUNICIPIO            VARCHAR(100),
    SG_UF                   VARCHAR(2),
    NU_CEP                  VARCHAR(8),
    ST_REGISTRO_ATIVO       VARCHAR(1)      NOT NULL DEFAULT 'S',
    CONSTRAINT PK_TB_PESSOA_JURIDICA
        PRIMARY KEY (CO_SEQ_PESSOA_JURIDICA),
    CONSTRAINT UK_TB_PESSOA_JURIDICA_NU_CNPJ
        UNIQUE (NU_CNPJ),
    CONSTRAINT CK_TB_PJ_ST_REGISTRO_ATIVO
        CHECK (ST_REGISTRO_ATIVO IN ('S', 'N'))
);

CREATE TABLE TB_SETOR (
    CO_SEQ_SETOR            BIGINT          NOT NULL DEFAULT NEXTVAL('SQ_TB_SETOR_CO_SEQ'),
    NO_SETOR                VARCHAR(200)    NOT NULL,
    SG_SETOR                VARCHAR(20)     NOT NULL,
    DS_SETOR                VARCHAR(500),
    ST_REGISTRO_ATIVO       VARCHAR(1)      NOT NULL DEFAULT 'S',
    CONSTRAINT PK_TB_SETOR
        PRIMARY KEY (CO_SEQ_SETOR),
    CONSTRAINT UK_TB_SETOR_SG_SETOR
        UNIQUE (SG_SETOR),
    CONSTRAINT CK_TB_SETOR_ST_REG_ATIVO
        CHECK (ST_REGISTRO_ATIVO IN ('S', 'N'))
);

CREATE TABLE TB_USUARIO (
    CO_SEQ_USUARIO          BIGINT          NOT NULL DEFAULT NEXTVAL('SQ_TB_USUARIO_CO_SEQ'),
    DS_SUB_OIDC             VARCHAR(255)    NOT NULL,
    CO_SEQ_PESSOA_FISICA    BIGINT          NOT NULL,
    DT_PRIMEIRO_ACESSO      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    DT_ULTIMO_ACESSO        TIMESTAMP WITHOUT TIME ZONE,
    ST_REGISTRO_ATIVO       VARCHAR(1)      NOT NULL DEFAULT 'S',
    CONSTRAINT PK_TB_USUARIO
        PRIMARY KEY (CO_SEQ_USUARIO),
    CONSTRAINT UK_TB_USUARIO_DS_SUB_OIDC
        UNIQUE (DS_SUB_OIDC),
    CONSTRAINT UK_TB_USUARIO_CO_SEQ_PF
        UNIQUE (CO_SEQ_PESSOA_FISICA),
    CONSTRAINT FK_TB_PESSOA_FISICA_TB_USUARIO
        FOREIGN KEY (CO_SEQ_PESSOA_FISICA) REFERENCES TB_PESSOA_FISICA (CO_SEQ_PESSOA_FISICA),
    CONSTRAINT CK_TB_USUARIO_ST_REG_ATIVO
        CHECK (ST_REGISTRO_ATIVO IN ('S', 'N'))
);

CREATE TABLE TB_ANALISTA (
    CO_SEQ_ANALISTA         BIGINT          NOT NULL DEFAULT NEXTVAL('SQ_TB_ANALISTA_CO_SEQ'),
    CO_SEQ_PESSOA_FISICA    BIGINT          NOT NULL,
    CO_SEQ_SETOR            BIGINT          NOT NULL,
    DT_VINCULO              DATE            NOT NULL,
    ST_REGISTRO_ATIVO       VARCHAR(1)      NOT NULL DEFAULT 'S',
    CONSTRAINT PK_TB_ANALISTA
        PRIMARY KEY (CO_SEQ_ANALISTA),
    CONSTRAINT FK_TB_PES_FIS_TB_ANALISTA
        FOREIGN KEY (CO_SEQ_PESSOA_FISICA) REFERENCES TB_PESSOA_FISICA (CO_SEQ_PESSOA_FISICA),
    CONSTRAINT FK_TB_SETOR_TB_ANALISTA
        FOREIGN KEY (CO_SEQ_SETOR) REFERENCES TB_SETOR (CO_SEQ_SETOR),
    CONSTRAINT CK_TB_ANALISTA_ST_REG_ATIVO
        CHECK (ST_REGISTRO_ATIVO IN ('S', 'N'))
);

CREATE TABLE TB_PROCESSO (
    CO_SEQ_PROCESSO         BIGINT          NOT NULL DEFAULT NEXTVAL('SQ_TB_PROCESSO_CO_SEQ'),
    NU_PROCESSO             VARCHAR(30)     NOT NULL,
    DS_ASSUNTO              VARCHAR(500)    NOT NULL,
    DT_ABERTURA             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CO_SEQ_USUARIO_ABERTURA BIGINT          NOT NULL,
    CO_SITUACAO_PROCESSO    VARCHAR(20)     NOT NULL DEFAULT 'ABERTO',
    ST_REGISTRO_ATIVO       VARCHAR(1)      NOT NULL DEFAULT 'S',
    CONSTRAINT PK_TB_PROCESSO
        PRIMARY KEY (CO_SEQ_PROCESSO),
    CONSTRAINT UK_TB_PROCESSO_NU_PROCESSO
        UNIQUE (NU_PROCESSO),
    CONSTRAINT FK_TB_USUARIO_TB_PROCESSO
        FOREIGN KEY (CO_SEQ_USUARIO_ABERTURA) REFERENCES TB_USUARIO (CO_SEQ_USUARIO),
    CONSTRAINT FK_TB_SIT_PROC_TB_PROCESSO
        FOREIGN KEY (CO_SITUACAO_PROCESSO) REFERENCES TB_SITUACAO_PROCESSO (CO_SITUACAO_PROCESSO),
    CONSTRAINT CK_TB_PROCESSO_ST_REG_ATIVO
        CHECK (ST_REGISTRO_ATIVO IN ('S', 'N'))
);

CREATE TABLE RL_PROCESSO_PARTE (
    CO_SEQ_PARTE            BIGINT          NOT NULL DEFAULT NEXTVAL('SQ_RL_PROCESSO_PARTE_CO_SEQ'),
    CO_SEQ_PROCESSO         BIGINT          NOT NULL,
    TP_PESSOA               VARCHAR(1)      NOT NULL,
    CO_SEQ_PESSOA_FISICA    BIGINT,
    CO_SEQ_PESSOA_JURIDICA  BIGINT,
    CO_TIPO_PARTE           VARCHAR(30)     NOT NULL,
    DT_VINCULO              TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ST_REGISTRO_ATIVO       VARCHAR(1)      NOT NULL DEFAULT 'S',
    CONSTRAINT PK_RL_PROCESSO_PARTE
        PRIMARY KEY (CO_SEQ_PARTE),
    CONSTRAINT FK_TB_PROCESSO_RL_PROC_PARTE
        FOREIGN KEY (CO_SEQ_PROCESSO) REFERENCES TB_PROCESSO (CO_SEQ_PROCESSO),
    CONSTRAINT FK_TB_PES_FIS_RL_PROC_PARTE
        FOREIGN KEY (CO_SEQ_PESSOA_FISICA) REFERENCES TB_PESSOA_FISICA (CO_SEQ_PESSOA_FISICA),
    CONSTRAINT FK_TB_PES_JUR_RL_PROC_PARTE
        FOREIGN KEY (CO_SEQ_PESSOA_JURIDICA) REFERENCES TB_PESSOA_JURIDICA (CO_SEQ_PESSOA_JURIDICA),
    CONSTRAINT FK_TB_TIPO_PARTE_RL_PROC_PARTE
        FOREIGN KEY (CO_TIPO_PARTE) REFERENCES TB_TIPO_PARTE (CO_TIPO_PARTE),
    CONSTRAINT CK_RL_PROC_PARTE_TP_PESSOA
        CHECK (TP_PESSOA IN ('F', 'J')),
    CONSTRAINT CK_RL_PROC_PARTE_PESSOA
        CHECK (
            (TP_PESSOA = 'F' AND CO_SEQ_PESSOA_FISICA IS NOT NULL AND CO_SEQ_PESSOA_JURIDICA IS NULL) OR
            (TP_PESSOA = 'J' AND CO_SEQ_PESSOA_JURIDICA IS NOT NULL AND CO_SEQ_PESSOA_FISICA IS NULL)
        ),
    CONSTRAINT CK_RL_PROC_PARTE_ST_REG_ATI
        CHECK (ST_REGISTRO_ATIVO IN ('S', 'N'))
);

CREATE TABLE TB_REGISTRO (
    CO_SEQ_REGISTRO         BIGINT          NOT NULL DEFAULT NEXTVAL('SQ_TB_REGISTRO_CO_SEQ'),
    CO_SEQ_PROCESSO         BIGINT          NOT NULL,
    DS_REGISTRO             TEXT            NOT NULL,
    DT_REGISTRO             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CO_SEQ_USUARIO          BIGINT          NOT NULL,
    ST_REGISTRO_ATIVO       VARCHAR(1)      NOT NULL DEFAULT 'S',
    CONSTRAINT PK_TB_REGISTRO
        PRIMARY KEY (CO_SEQ_REGISTRO),
    CONSTRAINT FK_TB_PROCESSO_TB_REGISTRO
        FOREIGN KEY (CO_SEQ_PROCESSO) REFERENCES TB_PROCESSO (CO_SEQ_PROCESSO),
    CONSTRAINT FK_TB_USUARIO_TB_REGISTRO
        FOREIGN KEY (CO_SEQ_USUARIO) REFERENCES TB_USUARIO (CO_SEQ_USUARIO),
    CONSTRAINT CK_TB_REGISTRO_ST_REG_ATIVO
        CHECK (ST_REGISTRO_ATIVO IN ('S', 'N'))
);

CREATE TABLE TH_TRAMITACAO (
    CO_SEQ_TRAMITACAO       BIGINT          NOT NULL DEFAULT NEXTVAL('SQ_TH_TRAMITACAO_CO_SEQ'),
    CO_SEQ_PROCESSO         BIGINT          NOT NULL,
    CO_SEQ_SETOR_ORIGEM     BIGINT,
    CO_SEQ_SETOR_DESTINO    BIGINT          NOT NULL,
    CO_SEQ_ANALISTA         BIGINT,
    DT_TRAMITACAO           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CO_SEQ_USUARIO          BIGINT          NOT NULL,
    DS_OBSERVACAO           VARCHAR(1000),
    CONSTRAINT PK_TH_TRAMITACAO
        PRIMARY KEY (CO_SEQ_TRAMITACAO),
    CONSTRAINT FK_TB_PROCESSO_TH_TRAMITACAO
        FOREIGN KEY (CO_SEQ_PROCESSO) REFERENCES TB_PROCESSO (CO_SEQ_PROCESSO),
    CONSTRAINT FK_TB_SETOR_TH_TRAM_ORIG
        FOREIGN KEY (CO_SEQ_SETOR_ORIGEM) REFERENCES TB_SETOR (CO_SEQ_SETOR),
    CONSTRAINT FK_TB_SETOR_TH_TRAM_DEST
        FOREIGN KEY (CO_SEQ_SETOR_DESTINO) REFERENCES TB_SETOR (CO_SEQ_SETOR),
    CONSTRAINT FK_TB_ANALISTA_TH_TRAMITACAO
        FOREIGN KEY (CO_SEQ_ANALISTA) REFERENCES TB_ANALISTA (CO_SEQ_ANALISTA),
    CONSTRAINT FK_TB_USUARIO_TH_TRAMITACAO
        FOREIGN KEY (CO_SEQ_USUARIO) REFERENCES TB_USUARIO (CO_SEQ_USUARIO)
);

-- =============================================================================
-- INDEXES
-- Padrão: IN_[TABELA]_[COLUNA] (regular) | IN_FK[TABELA]_[COLUNA] (FK)
-- =============================================================================

-- Busca textual
CREATE INDEX IN_TB_PES_FIS_NO_PESSOA
    ON TB_PESSOA_FISICA (NO_PESSOA_FISICA);

CREATE INDEX IN_TB_PES_JUR_NO_RAZ_SOC
    ON TB_PESSOA_JURIDICA (NO_RAZAO_SOCIAL);

-- FK: TB_USUARIO
CREATE INDEX IN_FKTB_USUARIO_CO_SEQ_PF
    ON TB_USUARIO (CO_SEQ_PESSOA_FISICA);

-- FK: TB_ANALISTA
CREATE INDEX IN_FKTB_ANALISTA_CO_SEQ_PF
    ON TB_ANALISTA (CO_SEQ_PESSOA_FISICA);

CREATE INDEX IN_FKTB_ANALISTA_CO_SEQ_SET
    ON TB_ANALISTA (CO_SEQ_SETOR);

-- TB_PROCESSO: FK e data
CREATE INDEX IN_FKTB_PROC_CO_SEQ_USR_ABE
    ON TB_PROCESSO (CO_SEQ_USUARIO_ABERTURA);

CREATE INDEX IN_FKTB_PROC_CO_SIT_PROC
    ON TB_PROCESSO (CO_SITUACAO_PROCESSO);

CREATE INDEX IN_TB_PROCESSO_DT_ABERTURA
    ON TB_PROCESSO (DT_ABERTURA);

-- RL_PROCESSO_PARTE: FKs
CREATE INDEX IN_FKRL_PROC_PARTE_CO_PROC
    ON RL_PROCESSO_PARTE (CO_SEQ_PROCESSO);

CREATE INDEX IN_FKRL_PROC_PARTE_CO_PF
    ON RL_PROCESSO_PARTE (CO_SEQ_PESSOA_FISICA);

CREATE INDEX IN_FKRL_PROC_PARTE_CO_PJ
    ON RL_PROCESSO_PARTE (CO_SEQ_PESSOA_JURIDICA);

-- TB_REGISTRO: FKs e data
CREATE INDEX IN_FKTB_REGISTRO_CO_SEQ_PROC
    ON TB_REGISTRO (CO_SEQ_PROCESSO);

CREATE INDEX IN_FKTB_REGISTRO_CO_SEQ_USU
    ON TB_REGISTRO (CO_SEQ_USUARIO);

CREATE INDEX IN_TB_REGISTRO_DT_REGISTRO
    ON TB_REGISTRO (DT_REGISTRO);

-- TH_TRAMITACAO: FKs e data
CREATE INDEX IN_FKTH_TRAM_CO_SEQ_PROC
    ON TH_TRAMITACAO (CO_SEQ_PROCESSO);

CREATE INDEX IN_FKTH_TRAM_CO_SEQ_ANAL
    ON TH_TRAMITACAO (CO_SEQ_ANALISTA);

CREATE INDEX IN_FKTH_TRAM_CO_SEQ_SET_D
    ON TH_TRAMITACAO (CO_SEQ_SETOR_DESTINO);

CREATE INDEX IN_FKTH_TRAM_CO_SEQ_SET_O
    ON TH_TRAMITACAO (CO_SEQ_SETOR_ORIGEM);

CREATE INDEX IN_FKTH_TRAM_CO_SEQ_USU
    ON TH_TRAMITACAO (CO_SEQ_USUARIO);

CREATE INDEX IN_TH_TRAMITACAO_DT_TRAM
    ON TH_TRAMITACAO (DT_TRAMITACAO);

-- =============================================================================
-- DADOS DE DOMÍNIO
-- =============================================================================

INSERT INTO TB_SITUACAO_PROCESSO (CO_SITUACAO_PROCESSO, DS_SITUACAO) VALUES
    ('ABERTO',        'Processo aberto, aguardando primeira tramitação'),
    ('EM_TRAMITACAO', 'Processo em tramitação entre setores'),
    ('ENCERRADO',     'Processo encerrado e finalizado');

INSERT INTO TB_TIPO_PARTE (CO_TIPO_PARTE, DS_TIPO_PARTE) VALUES
    ('REQUERENTE',    'Parte que solicita algo no processo'),
    ('REQUERIDO',     'Parte contra quem se requer algo'),
    ('INTERESSADO',   'Parte com interesse no resultado'),
    ('REPRESENTANTE', 'Representante legal de outra parte');

SELECT 'Estrutura criada com sucesso.' AS RESULTADO;
